set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i386)
set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_C_COMPILER wcl386)
set(CMAKE_CXX_COMPILER wcl386)
set(CMAKE_C_FLAGS "-bt=rdos")
set(CMAKE_EXE_LINKER_FLAGS "d all sys rdos op m op maplines op v op maxe=150")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

